### ISSUE TITLE
Error Throwing Instance

### ISSUE THREAD

**Issue by jacwilso** [AutonomyLab/libcreate#26]
I have installed the Boost dependencies with 'sudo apt-get install libboost-all-dev', 'sudo apt-get install aptitude', and 'aptitude search boost'. Then I followed the install instructions: 'cmake CMakeLists.txt', 'make', and 'sudo make install'.

When I go to run any of the examples with './create_demo' I receive an error:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():    Permission denied
Aborted (core dumped)
```

Any suggestions?

**Comment by jacobperron** [comment]
It sounds like permissions related to the serial connection. Try:
```bash
sudo usermod -a -G dialout $USER
```

And then logout and login again,

**Comment by jacwilso** [comment]
Thanks for the suggestion, but it didn't fix anything. Any other ideas?

**Comment by jacobperron** [comment]
Are you working with Create 1 or Create 2?

**Comment by jacobperron** [comment]
Ensure the the serial cable is connected, check that the device is listed as `ttyUSB0` (run `ls /dev`), and force permissions with `sudo chmod 777 /dev/ttyUSB0`.

**Comment by jacwilso** [comment]
I am working with create 2 and that last suggestion did it!! Thanks so much, I didn't have the right permissions set. 

I plan on using your library for a project, since you don't have documentation established yet do you have any warnings, suggestions, etc that might be useful? If not, thats ok. Thanks for the help thus far!

**Comment by jacobperron** [comment]
You can take a look at [create_autonomy](https://github.com/autonomylab/create_autonomy) for some documentation, but for API reference just use the header file [create.h](https://github.com/AutonomyLab/libcreate/blob/master/include/create/create.h)
