### ISSUE TITLE
Can't do catkin_make the catkin_ws because libcreate is not a ros file

### ISSUE THREAD

**Issue by SKT-Peanut** [AutonomyLab/libcreate#44]
Hey Jacob. So I clone libcreate into catkin_ws/src. However when I did catkin_make it doesn't work because libcreate is a plain c++ file not a ros package. How do I fix this problem? And how do I link it with create_autonomy?

**Comment by jacobperron** [comment]
Use the recommended isolated build command instead: `catkin_make_isolated`
I think that should do it.
