### ISSUE TITLE
Roomba i7?

### ISSUE THREAD

**Issue by peci1** [AutonomyLab/libcreate#56]
Hi, I got a Roomba i7 I can play with. I'd like to test this library. Do you have any idea where's its serial port connector? I watched some disassembly videos and it didn't seem to me there was one... Maybe now you can connect to the robot directly via bluetooth? At least the Android app wants bluetooth to be on during the setup...

**Comment by jacobperron** [comment]
AFAIK, 900 series Roombas or newer do not have a public serial API. So I doubt that libcreate would be compatible with Roomba i7.
