### ISSUE TITLE
Create::setAllMotors() called with uint8_t instead of float in Create::setMainMotor() etc.

### ISSUE THREAD

**Issue by danbsmith** [AutonomyLab/libcreate#61]
In the internal method for setting the main brush motor, for example:
```
  bool Create::setMainMotor(const float& main) {
    return setAllMotors(main, sideMotorPower, vacuumMotorPower);
  }
```
which is incorrect because while setAllMotors has the function signature:
`bool setAllMotors(const float& mainPower, const float& sidePower, const float& vacuumPower);`
while sideMotorPower and vacuumMotorPower are uint8_t.

**Comment by danbsmith** [comment]
I have opened a pull request for this issue #62

**Comment by jacobperron** [comment]
@danbsmith Thanks for the fix! Merged :slightly_smiling_face:
